export const jobIndustries = [
  "Agriculture",
  "Arts and Entertainment",
  "Automotive",
  "Banking and Finance",
  "Biotechnology",
  "Construction",
  "Consulting",
  "Education",
  "Energy and Utilities",
  "Engineering",
  "Healthcare and Medical",
  "Hospitality and Tourism",
  "Information Technology (IT)",
  "Insurance",
  "Legal",
  "Manufacturing",
  "Media and Communications",
  "Mining",
  "Pharmaceuticals",
  "Real Estate",
  "Retail",
  "Science and Research",
  "Social Services",
  "Telecommunications",
  "Transportation and Logistics",
  "Wholesale",
  "Nonprofit and Charitable Organizations",
  "Government and Public Administration",
]

export const jobTypes = ["Internship", "Full-Time", "Part-Time"]